name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v1
    - uses: conao3/setup-cask@master
      with:
        version: 0.8.4
    - name: Install dependencies
      run: 'cask install'
    - name: Run tests
      if: matrix.allow_failure != true
      run: 'cask exec ecukes'
    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'cask exec ecukes || true'
